//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avl_Seat
    {
        public int S_No { get; set; }
        public Nullable<decimal> Train_No { get; set; }
        public Nullable<int> First_Ac { get; set; }
        public Nullable<int> Second_Ac { get; set; }
        public Nullable<int> Sleeper { get; set; }
    
        public virtual Train_Details Train_Details { get; set; }
    }
}
