//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked_Ticket
    {
        public decimal Bookid { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<decimal> TrainNo { get; set; }
        public string PassengerName { get; set; }
        public double TotalFare { get; set; }
        public System.DateTime Booking_Date_Time { get; set; }
        public string Ticket_status { get; set; }
    
        public virtual Train_Details Train_Details { get; set; }
        public virtual User_detail User_detail { get; set; }
    }
}
